import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        paper: 'var(--paper)',
        'paper-tint': 'var(--paper-tint)',
        surface: {
          DEFAULT: 'var(--surface)',
          2: 'var(--surface-2)',
          3: 'var(--surface-3)',
        },
        ink: {
          DEFAULT: 'var(--ink)',
          2: 'var(--ink-2)',
          3: 'var(--ink-3)',
          4: 'var(--ink-4)',
        },
        line: {
          DEFAULT: 'var(--line)',
          2: 'var(--line-2)',
          strong: 'var(--line-strong)',
        },
        brick: {
          DEFAULT: 'var(--brick)',
          hover: 'var(--brick-hover)',
          soft: 'var(--brick-soft)',
          tint: 'var(--brick-tint)',
          ink: 'var(--brick-ink)',
        },
        sage: {
          DEFAULT: 'var(--sage)',
          soft: 'var(--sage-soft)',
        },
        ochre: {
          DEFAULT: 'var(--ochre)',
          soft: 'var(--ochre-soft)',
        },
        clay: {
          DEFAULT: 'var(--clay)',
          soft: 'var(--clay-soft)',
        },
        indigo: {
          DEFAULT: 'var(--indigo)',
          soft: 'var(--indigo-soft)',
        },
        primary: {
          DEFAULT: 'var(--brick)',
          50: 'var(--brick-tint)',
          100: 'var(--brick-soft)',
          200: 'var(--brick-soft)',
          300: 'var(--brick-soft)',
          400: 'var(--brick)',
          500: 'var(--brick)',
          600: 'var(--brick)',
          700: 'var(--brick-hover)',
          800: 'var(--brick-ink)',
          900: 'var(--brick-ink)',
        },
        accent: {
          DEFAULT: 'var(--ochre)',
          50: 'var(--ochre-soft)',
          100: 'var(--ochre-soft)',
          200: 'var(--ochre-soft)',
          300: 'var(--ochre-soft)',
          400: 'var(--ochre)',
          500: 'var(--ochre)',
          600: 'var(--ochre)',
          700: '#8c6424',
          800: '#664719',
          900: '#4b3211',
        },
        // 中性色调
        neutral: {
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          300: '#d1d5db',
          400: '#9ca3af',
          500: '#6b7280',
          600: '#4b5563',
          700: '#374151',
          800: '#1f2937',
          900: '#111827',
        },
        gray: {
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          300: '#d1d5db',
          400: '#9ca3af',
          500: '#6b7280',
          600: '#4b5563',
          700: '#374151',
          800: '#1f2937',
          900: '#111827',
        },
        // 状态颜色
        success: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
        warning: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        error: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        display: ['var(--font-display)'],
        mono: ['var(--font-mono)'],
      },
      borderRadius: {
        xs: 'var(--r-xs)',
        sm: 'var(--r-sm)',
        md: 'var(--r-md)',
        lg: 'var(--r-lg)',
        xl: 'var(--r-xl)',
        '2xl': 'var(--r-2xl)',
        full: 'var(--r-full)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        soft: 'var(--shadow-sm)',
        medium: 'var(--shadow-md)',
        strong: 'var(--shadow-lg)',
        warm: 'var(--shadow-xl)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
export default config
